import { type NextPage } from "next";
import Head from "next/head";

const GeneratePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form>
            <label className="">Prompt</label>
            <input type="text"></input>
            <button className="rounded px-6 py-4 bg-blue-400">Generate</button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
